"""Create a baseline migrations

Revision ID: 135bd067d146
Revises: 
Create Date: 2024-02-29 16:18:40.505379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '135bd067d147'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('address_id', sa.Integer(), nullable=True),
        sa.Column('status', sa.Boolean(), nullable=True),
        sa.Column('create_at', sa.DateTime(), nullable=True),
        # sa.ForeignKeyConstraint(['address'], ['address.id']),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('status')
    # ### end Alembic commands ###
