"""apply foreign key

Revision ID: 2e5b22d15562
Revises: d75c12f3088e
Create Date: 2024-02-29 12:01:08.708414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e5b22d15562'
down_revision: Union[str, None] = 'd75c12f3088e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'status', 'address', ['ip'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'status', type_='foreignkey')
    # ### end Alembic commands ###
